### ISSUE TITLE
Uninstall list is empty

### ISSUE THREAD

**Issue by Youpi-38** [ONElua/AutoPlugin2#56]
Hello,
I have had a problem since I switched from **AutoPlugin 1** to **AutoPlugin 2**. 
When I was using **AutoPlugin 1**, I could go to the uninstall section and there appeared the list of plug-ins on my PsVita.
Since I started using **AutoPlugin 2** this list is empty, as if there was no plug-in installed.
Do you have a solution or a manipulation to do ? 
Thank you so much.

(**PsVita 2000 3.60 ENSO 11**)

**Comment by DevDavisNunez** [comment]
Do you have the latest version of AutoPlugin II v1.05 installed?
There was a version that had the problem, but it was fixed.

**Comment by Youpi-38** [comment]
Thank you for your reply.
Yes, I have the latest version **1.05**.
When I went from **AutoPlugin 1** to **AutoPlugin 2** I installed version **1.03**, then did the update when it was **1.04** and finally the update **1.05**.
Since **1.03** I have this empty list problem.
I uninstall version **1.05** then reinstall but the problem remains.
:-(

**Comment by DevDavisNunez** [comment]
If I already upgrade to the newer version,
It is not a current bug, but a previous one, maybe in some previous version the content of its plugs was erased, so I recommend reinstalling it, and testing if they now appear in the list.

**Comment by Youpi-38** [comment]
Hello,
no sorry it still does not work.
This is what I did: I uninstall AutoPlugin 2 via **LiveArea**.
I then went to Vitashell (in each section) and I found an **AUTOPLUGIN2** folder, in **ux0/data**, which I deleted.
I downloaded the .vpk again to reinstall it.  But unfortunately the list remains empty ...... 
There may still be files from previous installations.
Maybe you can tell me how to delete any files that might remain after uninstalling?  For information, I use an **SD2VITA**.
Thank you ;-)

**Comment by ONElua** [comment]
Please show me your config.txt in ur0.

**Comment by Youpi-38** [comment]
Hello, here it is:

![image](https://user-images.githubusercontent.com/54135622/81439342-87438280-916e-11ea-881d-a35465d957b0.jpg)
![image](https://user-images.githubusercontent.com/54135622/81439378-95919e80-916e-11ea-80f7-142eb83c9aba.jpg)

;-)

**Comment by BaltazaR4** [comment]
Its a bug

**Comment by Youpi-38** [comment]
Hello,
thanks for your help but unfortunately after installing the new file the result is the same: empty ....

![image](https://user-images.githubusercontent.com/54135622/81469879-d5e13300-91e7-11ea-82eb-b2abc42050bb.jpg)
![image](https://user-images.githubusercontent.com/54135622/81469886-ebeef380-91e7-11ea-8645-9fc9264211b3.jpg)

:-(

**Comment by BaltazaR4** [comment]
Ok, for some reason after you downloaded the file has incorrect size, so, this time I zip it
https://drive.google.com/file/d/1CkNFgmwZelM7Vs2liYpy_BFj9esI8sWG/view?usp=drivesdk
The correct size is 14.66 kb
![2020-05-09-100037](https://user-images.githubusercontent.com/29612219/81475901-85140f00-91d4-11ea-8f0b-e34749a32c71.jpg)

**Comment by Youpi-38** [comment]
I just tried again but nothing helped.
I managed to save the file which is **14.66 KB**, still the same.
I again uninstalled everything then reinstalled **AutoPlugin 2 v1.05** but nothing .... **Empty list**.
I even found on my PC an **AutoPlugin 1 (vpk)** which I installed then updated to install **AutoPlugin 2** but nothing .... **Empty list**.
I'm lost.
;-)

**Comment by BaltazaR4** [comment]
Oh, so sorry, that file worked for me, anyways that issue has been taken care of, so it wont happen in the next update

**Comment by ONElua** [comment]
you have config un ux0:tai?

**Comment by ONElua** [comment]
please try
https://drive.google.com/file/d/1DJl_vE9uTVn0OQi0eKLFvQNmwPuZbb-d/view?usp=drivesdk

**Comment by Youpi-38** [comment]
> you have config un ux0:tai?

![image](https://user-images.githubusercontent.com/54135622/81493882-81e85400-92a4-11ea-8b3f-692c4e1542b1.jpg)

Hello,
here is my ux0: tai Config.txt ;-).
I forgot to say (if it helps) that yesterday when I installed **AutoPlugin 1** again, the list of plugins to uninstall was "full".

**Comment by ONElua** [comment]
@Youpi-38 hi, please try
https://drive.google.com/file/d/1DJl_vE9uTVn0OQi0eKLFvQNmwPuZbb-d/view?usp=drivesdk

**Comment by Youpi-38** [comment]
Hello, sorry I couldn't try just now.  Is it a .vpk that should be installed on the PsVita and launched?

**Comment by ONElua** [comment]
yes, 
now all the plugins are installed in ur0

**Comment by Youpi-38** [comment]
Thank you very much for your work, your help and your patient.  ;-)
